apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      task: mysql
  template:
    metadata:
      labels:
        app: mysql
        task: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          tty: true
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: mysql-db
            - name: MYSQL_USER
              value: jondoe
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mysql-secret
                    key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
